"""
Usage:
    python manage.py seed_questions

Story: "Mars Return Mission – Space Station Emergency"
Age group: 10–16 (school students)

L1 — Navigation System Failure   → Easy
L2 — Power Distribution Failure  → Easy
L3 — Communication Breakdown     → Medium
L4 — Life Support Critical       → Medium
L5 — Engine Core & Landing       → Hard

10 questions × 5 subjects × 5 levels = 250 questions total.
Each session randomly selects 3 per subject = 15 per level.
Safe to re-run (get_or_create on level+subject+text).
"""

from django.core.management.base import BaseCommand
from apps.game.models import Question
from apps.core.constants import LEVEL_DIFFICULTY, Subject


# ─── LEVEL 1 ── Navigation System Failure (EASY) ─────────────────────────────

L1 = {

    Subject.MATH: [
        {"text": "🚀 The navigation computer needs speed. Your spaceship travels 600 km in 3 hours. Average speed?",
         "option_a": "100 km/h", "option_b": "150 km/h", "option_c": "200 km/h", "option_d": "250 km/h", "correct_option": "C",
         "explanation": "Speed = Distance ÷ Time = 600 ÷ 3 = 200 km/h."},
        {"text": "🛸 Ship needs to travel 1,200 km total and has covered 450 km. How much further?",
         "option_a": "650 km", "option_b": "700 km", "option_c": "750 km", "option_d": "800 km", "correct_option": "C",
         "explanation": "1200 − 450 = 750 km."},
        {"text": "📡 Ship is at position 48 and needs to reach 120. How many units must it move?",
         "option_a": "62", "option_b": "68", "option_c": "72", "option_d": "78", "correct_option": "C",
         "explanation": "120 − 48 = 72 units."},
        {"text": "⏱ Journey to Earth takes 15 hours. How many minutes is that?",
         "option_a": "750", "option_b": "800", "option_c": "850", "option_d": "900", "correct_option": "D",
         "explanation": "15 × 60 = 900 minutes."},
        {"text": "🌍 Map scale: 1 cm = 500 km. Map distance = 8 cm. Real distance?",
         "option_a": "3,500 km", "option_b": "4,000 km", "option_c": "4,500 km", "option_d": "5,000 km", "correct_option": "B",
         "explanation": "8 × 500 = 4,000 km."},
        {"text": "🔢 Solve for the navigation fix: 7 × (4 + 6) − 20 = ?",
         "option_a": "40", "option_b": "48", "option_c": "50", "option_d": "56", "correct_option": "C",
         "explanation": "7 × 10 − 20 = 70 − 20 = 50."},
        {"text": "📐 Full rotation = 360°. Ship has turned 135°. How many degrees remain?",
         "option_a": "205°", "option_b": "215°", "option_c": "225°", "option_d": "235°", "correct_option": "C",
         "explanation": "360 − 135 = 225°."},
        {"text": "🚀 5 navigation boosters, each uses 12 fuel units/hour. Fuel used in 3 hours?",
         "option_a": "150", "option_b": "160", "option_c": "170", "option_d": "180", "correct_option": "D",
         "explanation": "5 × 12 × 3 = 180 units."},
        {"text": "💻 A number divided by itself always equals?",
         "option_a": "0", "option_b": "1", "option_c": "The number itself", "option_d": "Undefined", "correct_option": "B",
         "explanation": "Any non-zero number ÷ itself = 1. e.g. 7 ÷ 7 = 1."},
        {"text": "🌠 The ship has 3 engines each producing 250 N of thrust. Total thrust?",
         "option_a": "500 N", "option_b": "650 N", "option_c": "750 N", "option_d": "800 N", "correct_option": "C",
         "explanation": "3 × 250 = 750 N total thrust."},
    ],

    Subject.COMPUTER: [
        {"text": "💾 Navigation computer data: binary 1010 in decimal equals?",
         "option_a": "8", "option_b": "9", "option_c": "10", "option_d": "12", "correct_option": "C",
         "explanation": "1010 = 1×8 + 0×4 + 1×2 + 0×1 = 10."},
        {"text": "🖥 'IF altitude > 500 THEN fire boosters'. Altitude = 450. What happens?",
         "option_a": "Boosters fire", "option_b": "Boosters do NOT fire", "option_c": "System crashes", "option_d": "Nothing", "correct_option": "B",
         "explanation": "450 is not > 500, condition is false — boosters don't fire."},
        {"text": "🔁 'REPEAT 4 TIMES: add 25 to speed'. Starting speed = 100. Final speed?",
         "option_a": "125", "option_b": "150", "option_c": "175", "option_d": "200", "correct_option": "D",
         "explanation": "100 + (4 × 25) = 200."},
        {"text": "📂 List of waypoints: [A, B, C, D, E, F]. What is at index 3 (counting from 0)?",
         "option_a": "B", "option_b": "C", "option_c": "D", "option_d": "E", "correct_option": "C",
         "explanation": "Index 0=A, 1=B, 2=C, 3=D."},
        {"text": "🔣 CPU stands for?",
         "option_a": "Central Program Utility", "option_b": "Central Processing Unit", "option_c": "Computer Power Unit", "option_d": "Control Processing Unit", "correct_option": "B",
         "explanation": "CPU = Central Processing Unit — the brain of a computer."},
        {"text": "🧮 Navigation AI counts down from 10 to 1. How many numbers does it say?",
         "option_a": "9", "option_b": "10", "option_c": "11", "option_d": "12", "correct_option": "B",
         "explanation": "10, 9, 8, 7, 6, 5, 4, 3, 2, 1 — that is 10 numbers."},
        {"text": "🔒 Navigation password is 4 binary digits (bits). How many different passwords possible?",
         "option_a": "8", "option_b": "16", "option_c": "32", "option_d": "64", "correct_option": "B",
         "explanation": "4 bits = 2⁴ = 16 combinations."},
        {"text": "📟 Algorithm: 'Add 5 to X three times, starting X = 0'. Final X?",
         "option_a": "5", "option_b": "10", "option_c": "15", "option_d": "20", "correct_option": "C",
         "explanation": "0 + 5 + 5 + 5 = 15."},
        {"text": "🖱 Which is an INPUT device for the ship's computer?",
         "option_a": "Screen", "option_b": "Speaker", "option_c": "Keyboard", "option_d": "Printer", "correct_option": "C",
         "explanation": "Keyboard is input. Screen, speaker, printer are output devices."},
        {"text": "🔧 The process of finding and fixing bugs in a program is called?",
         "option_a": "Compiling", "option_b": "Debugging", "option_c": "Uploading", "option_d": "Booting", "correct_option": "B",
         "explanation": "Debugging is finding and fixing errors in a program."},
    ],

    Subject.PHYSICS: [
        {"text": "🚀 'An object in motion stays in motion unless a force acts on it.' Which Newton's Law?",
         "option_a": "First Law", "option_b": "Second Law", "option_c": "Third Law", "option_d": "Fourth Law", "correct_option": "A",
         "explanation": "Newton's First Law (Law of Inertia)."},
        {"text": "⚡ F = ma. Mass = 500 kg, acceleration = 2 m/s². Force?",
         "option_a": "500 N", "option_b": "750 N", "option_c": "1000 N", "option_d": "1500 N", "correct_option": "C",
         "explanation": "F = 500 × 2 = 1000 N."},
        {"text": "🌍 Far from any planet, which is TRUE about the spaceship?",
         "option_a": "Falls downward constantly", "option_b": "Gravity pulls it strongly", "option_c": "It experiences near-zero gravity (microgravity)", "option_d": "It moves slower", "correct_option": "C",
         "explanation": "In deep space, far from massive bodies, gravity is nearly zero — microgravity."},
        {"text": "🔴 Ship fires thruster LEFT to move RIGHT. Which Newton's Law?",
         "option_a": "First Law", "option_b": "Second Law", "option_c": "Third Law", "option_d": "Law of Gravity", "correct_option": "C",
         "explanation": "Third Law: for every action there is an equal and opposite reaction."},
        {"text": "🌠 What is the SI unit of speed?",
         "option_a": "km/h", "option_b": "m/s", "option_c": "m/s²", "option_d": "N", "correct_option": "B",
         "explanation": "SI unit of speed is metres per second (m/s)."},
        {"text": "⏩ Ship accelerates from 0 to 60 m/s in 10 seconds. Acceleration?",
         "option_a": "3 m/s²", "option_b": "5 m/s²", "option_c": "6 m/s²", "option_d": "10 m/s²", "correct_option": "C",
         "explanation": "a = (60 − 0) ÷ 10 = 6 m/s²."},
        {"text": "🌙 Which correctly defines speed?",
         "option_a": "Mass × Acceleration", "option_b": "Distance × Time", "option_c": "Distance ÷ Time", "option_d": "Force ÷ Mass", "correct_option": "C",
         "explanation": "Speed = Distance ÷ Time."},
        {"text": "🔵 Can the crew OUTSIDE the ship hear the boosters in space?",
         "option_a": "Yes, clearly", "option_b": "Yes, but faintly", "option_c": "No, space is a vacuum", "option_d": "Only if they shout", "correct_option": "C",
         "explanation": "Sound requires a medium. Space is a vacuum — no medium, no sound."},
        {"text": "💡 Light from the navigation beacon travels at 300,000 km/s. This is the speed of ___.",
         "option_a": "Sound", "option_b": "Light", "option_c": "Radio", "option_d": "Electricity", "correct_option": "B",
         "explanation": "300,000 km/s is the speed of light (c)."},
        {"text": "⚖ Spaceship has mass 2,000 kg on Earth. What is its mass in space?",
         "option_a": "0 kg", "option_b": "Less than 2,000 kg", "option_c": "2,000 kg — mass never changes", "option_d": "More than 2,000 kg", "correct_option": "C",
         "explanation": "Mass is the amount of matter — it never changes. Only weight changes with gravity."},
    ],

    Subject.CHEMISTRY: [
        {"text": "🧪 Matter exists in three common states. Which is NOT a state of matter?",
         "option_a": "Solid", "option_b": "Liquid", "option_c": "Energy", "option_d": "Gas", "correct_option": "C",
         "explanation": "The three states are solid, liquid, and gas. Energy is not a state of matter."},
        {"text": "🌡 When a solid is heated enough it turns liquid. This is called?",
         "option_a": "Freezing", "option_b": "Evaporation", "option_c": "Melting", "option_d": "Condensation", "correct_option": "C",
         "explanation": "Melting is when a solid absorbs heat and becomes a liquid."},
        {"text": "💧 Water found as ice on Mars has chemical formula?",
         "option_a": "HO", "option_b": "H₂O", "option_c": "OH₂", "option_d": "H₂O₂", "correct_option": "B",
         "explanation": "Water is H₂O — two hydrogen atoms bonded to one oxygen atom."},
        {"text": "🔬 Everything is made of tiny particles called ___.",
         "option_a": "Cells", "option_b": "Atoms", "option_c": "Pixels", "option_d": "Bits", "correct_option": "B",
         "explanation": "All matter is made of atoms — the smallest building blocks of elements."},
        {"text": "🧲 Mars sample container is made of iron. Chemical symbol for Iron?",
         "option_a": "Ir", "option_b": "Io", "option_c": "Fe", "option_d": "In", "correct_option": "C",
         "explanation": "Fe comes from Latin 'Ferrum' meaning iron."},
        {"text": "⚗ Sand and water mixture separated by which method?",
         "option_a": "Boiling", "option_b": "Filtration", "option_c": "Melting", "option_d": "Burning", "correct_option": "B",
         "explanation": "Filtration separates an insoluble solid (sand) from a liquid (water)."},
        {"text": "🌿 Oxygen's chemical symbol is ___.",
         "option_a": "O — oxygen symbol is O", "option_b": "Ox", "option_c": "Om", "option_d": "Og", "correct_option": "A",
         "explanation": "Oxygen's chemical symbol is O. As a gas we breathe it exists as O₂."},
        {"text": "🧊 Water vapour turns directly to ice in the cold cargo bay. Gas → solid directly is called?",
         "option_a": "Condensation", "option_b": "Evaporation", "option_c": "Sublimation", "option_d": "Deposition", "correct_option": "D",
         "explanation": "Deposition: gas turns directly to solid without passing through liquid."},
        {"text": "🔥 The ship's fuel burns to produce energy. Burning is a ___ reaction.",
         "option_a": "Physical change", "option_b": "Chemical change", "option_c": "Nuclear change", "option_d": "Magnetic change", "correct_option": "B",
         "explanation": "Burning (combustion) is a chemical change — new substances are produced."},
        {"text": "🌡 Mars can reach −80°C. On Celsius scale, freezing point of water is?",
         "option_a": "−100°C", "option_b": "0°C", "option_c": "100°C", "option_d": "37°C", "correct_option": "B",
         "explanation": "Water freezes at 0°C and boils at 100°C on the Celsius scale."},
    ],

    Subject.GK: [
        {"text": "🌍 Mars is the ___ planet from the Sun.",
         "option_a": "Third", "option_b": "Fourth", "option_c": "Fifth", "option_d": "Second", "correct_option": "B",
         "explanation": "Order: Mercury, Venus, Earth, Mars… Mars is 4th."},
        {"text": "🚀 First human to walk on the Moon?",
         "option_a": "Yuri Gagarin", "option_b": "Buzz Aldrin", "option_c": "Neil Armstrong", "option_d": "John Glenn", "correct_option": "C",
         "explanation": "Neil Armstrong walked on the Moon on July 20, 1969 (Apollo 11)."},
        {"text": "🌠 How many planets are in our Solar System?",
         "option_a": "7", "option_b": "8", "option_c": "9", "option_d": "10", "correct_option": "B",
         "explanation": "8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune."},
        {"text": "🛸 NASA stands for?",
         "option_a": "National Aeronautics and Space Administration", "option_b": "National Aerospace Science Agency", "option_c": "North American Space Authority", "option_d": "National Aviation Satellite Agency", "correct_option": "A",
         "explanation": "NASA = National Aeronautics and Space Administration."},
        {"text": "🌙 What causes day and night on Earth?",
         "option_a": "Earth revolving around the Sun", "option_b": "The Moon blocking the Sun", "option_c": "Earth rotating on its axis", "option_d": "The Sun moving around Earth", "correct_option": "C",
         "explanation": "Earth spins (rotates) on its axis once every 24 hours — causing day and night."},
        {"text": "⭐ Our Sun is a ___.",
         "option_a": "Planet", "option_b": "Moon", "option_c": "Star", "option_d": "Comet", "correct_option": "C",
         "explanation": "The Sun is a star — a massive ball of hot gas producing energy through nuclear fusion."},
        {"text": "🪐 Largest planet in our Solar System?",
         "option_a": "Saturn", "option_b": "Neptune", "option_c": "Uranus", "option_d": "Jupiter", "correct_option": "D",
         "explanation": "Jupiter is the largest planet."},
        {"text": "🔭 A light-year is a unit of ___.",
         "option_a": "Time", "option_b": "Distance", "option_c": "Speed", "option_d": "Mass", "correct_option": "B",
         "explanation": "A light-year is the distance light travels in one year (~9.46 trillion km)."},
        {"text": "🌍 Which gas makes up most of Earth's atmosphere?",
         "option_a": "Oxygen", "option_b": "Carbon dioxide", "option_c": "Nitrogen", "option_d": "Hydrogen", "correct_option": "C",
         "explanation": "Nitrogen makes up about 78% of Earth's atmosphere."},
        {"text": "🛰 Name of the space station currently orbiting Earth?",
         "option_a": "Mir", "option_b": "Skylab", "option_c": "International Space Station (ISS)", "option_d": "Apollo Station", "correct_option": "C",
         "explanation": "The ISS has been continuously occupied since November 2000."},
    ],
}


# ─── LEVEL 2 ── Power Distribution Failure (EASY) ────────────────────────────

L2 = {

    Subject.MATH: [
        {"text": "⚡ Power grid has 4 batteries, each storing 150 energy units. Total energy available?",
         "option_a": "450", "option_b": "500", "option_c": "550", "option_d": "600", "correct_option": "D",
         "explanation": "4 × 150 = 600 units."},
        {"text": "🔋 Ship uses 80 energy units/hour. 480 units remain. Hours of power left?",
         "option_a": "4", "option_b": "5", "option_c": "6", "option_d": "7", "correct_option": "C",
         "explanation": "480 ÷ 80 = 6 hours."},
        {"text": "💡 Backup reactor produces 45 units/minute. Units produced in 8 minutes?",
         "option_a": "320", "option_b": "340", "option_c": "360", "option_d": "380", "correct_option": "C",
         "explanation": "45 × 8 = 360 units."},
        {"text": "🔌 Power leaks at 15 units/minute. After 7 minutes, how much has leaked?",
         "option_a": "95", "option_b": "100", "option_c": "105", "option_d": "110", "correct_option": "C",
         "explanation": "15 × 7 = 105 units leaked."},
        {"text": "🔢 Power = Voltage × Current. Voltage = 12 V, Current = 5 A. Power?",
         "option_a": "17 W", "option_b": "40 W", "option_c": "60 W", "option_d": "72 W", "correct_option": "C",
         "explanation": "P = V × I = 12 × 5 = 60 Watts."},
        {"text": "🧮 Zone A=120W, Zone B=85W, Zone C=95W. Total power used?",
         "option_a": "280 W", "option_b": "290 W", "option_c": "300 W", "option_d": "310 W", "correct_option": "C",
         "explanation": "120 + 85 + 95 = 300 W."},
        {"text": "⚡ Energy reserve = 1,000 units. Crew used 35% to fix the grid. Units used?",
         "option_a": "300", "option_b": "325", "option_c": "350", "option_d": "375", "correct_option": "C",
         "explanation": "35% of 1000 = 350 units."},
        {"text": "🔋 Two generators in ratio 2:3 produce 500 units total. Larger generator produces?",
         "option_a": "150", "option_b": "200", "option_c": "250", "option_d": "300", "correct_option": "D",
         "explanation": "Larger share = 3/5 × 500 = 300 units."},
        {"text": "📊 Power reads 240 at 08:00, 168 at 10:00. Average consumption per hour?",
         "option_a": "30 units/hr", "option_b": "36 units/hr", "option_c": "40 units/hr", "option_d": "48 units/hr", "correct_option": "B",
         "explanation": "Used = 72 units in 2 hours. 72 ÷ 2 = 36 units/hr."},
        {"text": "🌡 Engine room temperature rises 4°C every 10 minutes. Starting at 20°C, temp after 30 mins?",
         "option_a": "28°C", "option_b": "30°C", "option_c": "32°C", "option_d": "34°C", "correct_option": "C",
         "explanation": "3 × 4 = 12°C rise. 20 + 12 = 32°C."},
    ],

    Subject.COMPUTER: [
        {"text": "💻 'WHILE power < 100: add 10'. Starting at 70, how many times does the loop run?",
         "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "5", "correct_option": "B",
         "explanation": "70→80 (1), 80→90 (2), 90→100 (3). Condition fails at 100. Runs 3 times."},
        {"text": "🔋 Which data type holds the whole number 42?",
         "option_a": "String", "option_b": "Boolean", "option_c": "Integer", "option_d": "Float", "correct_option": "C",
         "explanation": "42 is a whole number — stored as an Integer."},
        {"text": "⚙ 'IF power_level == 0 OR temperature > 100'. Which logical operator is used?",
         "option_a": "AND", "option_b": "NOT", "option_c": "OR", "option_d": "XOR", "correct_option": "C",
         "explanation": "OR is true if EITHER part is true."},
        {"text": "📋 Power log list: [100, 90, 75, 60, 50]. What is the LAST value?",
         "option_a": "100", "option_b": "75", "option_c": "60", "option_d": "50", "correct_option": "D",
         "explanation": "The last element of [100, 90, 75, 60, 50] is 50."},
        {"text": "🔄 RAM stands for?",
         "option_a": "Read All Memory", "option_b": "Random Access Memory", "option_c": "Run Application Module", "option_d": "Rapid Action Memory", "correct_option": "B",
         "explanation": "RAM = Random Access Memory — the computer's short-term working memory."},
        {"text": "🖥 Computer shows 'ERROR: DIVISION BY ZERO'. What does this mean?",
         "option_a": "Battery is empty", "option_b": "A number was divided by 0, which is impossible", "option_c": "Screen is broken", "option_d": "Program ran too fast", "correct_option": "B",
         "explanation": "Division by zero is mathematically undefined and causes an error in programs."},
        {"text": "💾 Power computer needs 256 MB. How many GB? (1 GB = 1024 MB)",
         "option_a": "0.25 GB", "option_b": "0.5 GB", "option_c": "1 GB", "option_d": "2 GB", "correct_option": "A",
         "explanation": "256 ÷ 1024 = 0.25 GB."},
        {"text": "🔐 Power system protected by a 3-digit code (digits 0–9). How many possible codes?",
         "option_a": "100", "option_b": "500", "option_c": "1000", "option_d": "9999", "correct_option": "C",
         "explanation": "10 × 10 × 10 = 1,000 possible codes."},
        {"text": "🔁 'FOR i = 1 TO 5: PRINT i'. Last number printed?",
         "option_a": "4", "option_b": "5", "option_c": "6", "option_d": "0", "correct_option": "B",
         "explanation": "The loop prints 1, 2, 3, 4, 5. Last value is 5."},
        {"text": "📡 Decimal 7 in binary is?",
         "option_a": "0101", "option_b": "0110", "option_c": "0111", "option_d": "1000", "correct_option": "C",
         "explanation": "7 = 4+2+1 = 111 in binary (0111 with leading zero)."},
    ],

    Subject.PHYSICS: [
        {"text": "⚡ Which is the unit of electrical energy?",
         "option_a": "Watt", "option_b": "Joule", "option_c": "Newton", "option_d": "Ampere", "correct_option": "B",
         "explanation": "Joule (J) is the SI unit of energy, including electrical energy."},
        {"text": "🔋 Ohm's Law: V = I × R. V = 24 V, R = 6 Ω. Current I?",
         "option_a": "2 A", "option_b": "3 A", "option_c": "4 A", "option_d": "6 A", "correct_option": "C",
         "explanation": "I = V ÷ R = 24 ÷ 6 = 4 A."},
        {"text": "💡 One bulb in a SERIES circuit breaks. What happens to the others?",
         "option_a": "They get brighter", "option_b": "They continue normally", "option_c": "They all go out", "option_d": "They flash", "correct_option": "C",
         "explanation": "In series, the circuit is one loop. One break stops current — all go out."},
        {"text": "🌡 What is the SI unit of temperature?",
         "option_a": "Celsius", "option_b": "Fahrenheit", "option_c": "Kelvin", "option_d": "Joule", "correct_option": "C",
         "explanation": "The SI unit of temperature is Kelvin (K). 0 K = −273°C (absolute zero)."},
        {"text": "🔌 P = V × I. Device uses 6 V at 2 A. Power?",
         "option_a": "3 W", "option_b": "8 W", "option_c": "12 W", "option_d": "16 W", "correct_option": "C",
         "explanation": "P = 6 × 2 = 12 W."},
        {"text": "⚡ The backup battery converts chemical energy to ___.",
         "option_a": "Heat energy", "option_b": "Sound energy", "option_c": "Electrical energy", "option_d": "Light energy", "correct_option": "C",
         "explanation": "Batteries convert stored chemical energy into electrical energy."},
        {"text": "🔋 Energy cannot be created or destroyed — only converted. This is the Law of ___.",
         "option_a": "Gravity", "option_b": "Motion", "option_c": "Conservation of Energy", "option_d": "Thermodynamics", "correct_option": "C",
         "explanation": "The Law of Conservation of Energy states energy cannot be created or destroyed."},
        {"text": "🌡 Generator produces heat AND light. This is energy ___.",
         "option_a": "Creation", "option_b": "Destruction", "option_c": "Conversion", "option_d": "Multiplication", "correct_option": "C",
         "explanation": "Energy conversion means changing energy from one form to another."},
        {"text": "💡 60-watt bulb runs 2 hours. Energy used in watt-hours?",
         "option_a": "30 Wh", "option_b": "60 Wh", "option_c": "90 Wh", "option_d": "120 Wh", "correct_option": "D",
         "explanation": "Energy = Power × Time = 60 × 2 = 120 watt-hours."},
        {"text": "🔌 Best conductor of electricity?",
         "option_a": "Rubber", "option_b": "Wood", "option_c": "Plastic", "option_d": "Copper", "correct_option": "D",
         "explanation": "Copper is an excellent electrical conductor, widely used in wires."},
    ],

    Subject.CHEMISTRY: [
        {"text": "🔥 Ship's fuel cell combines H₂ + O₂ → H₂O + energy. This reaction type is?",
         "option_a": "Decomposition", "option_b": "Combustion", "option_c": "Synthesis (combination)", "option_d": "Displacement", "correct_option": "C",
         "explanation": "Synthesis: two or more substances combine to form one new substance."},
        {"text": "⚗ What does a catalyst do?",
         "option_a": "Slows a reaction", "option_b": "Speeds up a reaction without being used up", "option_c": "Stops a reaction", "option_d": "Changes the products", "correct_option": "B",
         "explanation": "A catalyst speeds up a chemical reaction but is not consumed in the process."},
        {"text": "🌡 At 500°C, is iron (melting point ~1538°C) solid, liquid, or gas?",
         "option_a": "Solid", "option_b": "Liquid", "option_c": "Gas", "option_d": "Plasma", "correct_option": "A",
         "explanation": "Iron melts at ~1538°C. At 500°C it is still solid."},
        {"text": "🔋 Energy stored in chemical bonds, released during reactions is called?",
         "option_a": "Kinetic energy", "option_b": "Chemical energy", "option_c": "Nuclear energy", "option_d": "Mechanical energy", "correct_option": "B",
         "explanation": "Chemical energy is energy stored in chemical bonds."},
        {"text": "🧪 Hydrogen's chemical symbol is?",
         "option_a": "Hy", "option_b": "Hg", "option_c": "H", "option_d": "He", "correct_option": "C",
         "explanation": "Hydrogen's symbol is H. (Hg is Mercury, He is Helium.)"},
        {"text": "⚡ Electrolysis of water (H₂O) produces which two gases?",
         "option_a": "Nitrogen and CO₂", "option_b": "Hydrogen and Oxygen", "option_c": "Helium and Oxygen", "option_d": "Hydrogen and Nitrogen", "correct_option": "B",
         "explanation": "Electrolysis of water produces hydrogen (H₂) and oxygen (O₂)."},
        {"text": "🔥 Carbon-based fuel burns. Chemical formula of carbon dioxide produced?",
         "option_a": "CO", "option_b": "C₂O", "option_c": "CO₂", "option_d": "C₂O₃", "correct_option": "C",
         "explanation": "Carbon dioxide = CO₂ (one carbon, two oxygen atoms)."},
        {"text": "🌡 Mercury is a metal that is liquid at room temperature. Its chemical symbol is?",
         "option_a": "Me", "option_b": "Mr", "option_c": "Mc", "option_d": "Hg", "correct_option": "D",
         "explanation": "Mercury's symbol is Hg, from Latin 'Hydrargyrum' meaning liquid silver."},
        {"text": "⚗ Acids have pH less than 7. Which is an ACID?",
         "option_a": "Baking soda (pH 9)", "option_b": "Pure water (pH 7)", "option_c": "Lemon juice (pH 2)", "option_d": "Bleach (pH 12)", "correct_option": "C",
         "explanation": "Lemon juice has pH ~2, less than 7 — it is an acid."},
        {"text": "🔬 Iron rusts by reacting with water and ___.",
         "option_a": "Nitrogen", "option_b": "Carbon dioxide", "option_c": "Oxygen", "option_d": "Hydrogen", "correct_option": "C",
         "explanation": "Rusting requires iron, water, and oxygen: 4Fe + 3O₂ + H₂O → rust."},
    ],

    Subject.GK: [
        {"text": "🌍 Which planet is known as the Red Planet?",
         "option_a": "Venus", "option_b": "Mars", "option_c": "Jupiter", "option_d": "Saturn", "correct_option": "B",
         "explanation": "Mars is the Red Planet — its surface is covered in reddish iron oxide (rust)."},
        {"text": "⚡ Who demonstrated that lightning is electrical using a kite experiment?",
         "option_a": "Thomas Edison", "option_b": "Nikola Tesla", "option_c": "Benjamin Franklin", "option_d": "Michael Faraday", "correct_option": "C",
         "explanation": "Benjamin Franklin's kite experiment demonstrated that lightning is electrical."},
        {"text": "🔋 Who invented the first practical electric light bulb?",
         "option_a": "Nikola Tesla", "option_b": "Alexander Graham Bell", "option_c": "Thomas Edison", "option_d": "Michael Faraday", "correct_option": "C",
         "explanation": "Thomas Edison developed the first practical incandescent light bulb in 1879."},
        {"text": "☀ Nearest star to Earth (other than the Sun)?",
         "option_a": "Sirius", "option_b": "Betelgeuse", "option_c": "Proxima Centauri", "option_d": "Polaris", "correct_option": "C",
         "explanation": "Proxima Centauri is about 4.24 light-years away."},
        {"text": "🌊 What covers most of Earth's surface?",
         "option_a": "Land", "option_b": "Ice", "option_c": "Water (oceans)", "option_d": "Forests", "correct_option": "C",
         "explanation": "About 71% of Earth's surface is covered by water."},
        {"text": "🧬 DNA stands for?",
         "option_a": "Deoxyribonucleic Acid", "option_b": "Dioxynucleic Acid", "option_c": "Double Nucleic Arrangement", "option_d": "Dynamic Nucleotide Assembly", "correct_option": "A",
         "explanation": "DNA = Deoxyribonucleic Acid — the molecule carrying genetic information."},
        {"text": "🔭 Who invented the telescope?",
         "option_a": "Isaac Newton", "option_b": "Galileo Galilei", "option_c": "Hans Lippershey", "option_d": "Copernicus", "correct_option": "C",
         "explanation": "Hans Lippershey invented the first practical telescope in 1608."},
        {"text": "🌋 The three types of rocks are?",
         "option_a": "Hard, Soft, Medium", "option_b": "Igneous, Sedimentary, Metamorphic", "option_c": "Volcanic, River, Mountain", "option_d": "Limestone, Granite, Marble", "correct_option": "B",
         "explanation": "Igneous (from magma), Sedimentary (from layers), Metamorphic (changed by heat/pressure)."},
        {"text": "🧲 A magnet's two poles are called?",
         "option_a": "Positive and Negative", "option_b": "North and South", "option_c": "East and West", "option_d": "Hot and Cold", "correct_option": "B",
         "explanation": "Every magnet has a North pole and a South pole. Opposite poles attract."},
        {"text": "🌿 Process plants use to make food using sunlight?",
         "option_a": "Respiration", "option_b": "Digestion", "option_c": "Photosynthesis", "option_d": "Absorption", "correct_option": "C",
         "explanation": "Photosynthesis: plants use sunlight, CO₂, and water to make glucose and oxygen."},
    ],
}


# ─── LEVEL 3 ── Communication Breakdown (MEDIUM) ─────────────────────────────

L3 = {

    Subject.MATH: [
        {"text": "📡 Signal travels 300,000 km/s. Time to travel 900,000 km?",
         "option_a": "1 second", "option_b": "2 seconds", "option_c": "3 seconds", "option_d": "4 seconds", "correct_option": "C",
         "explanation": "Time = 900,000 ÷ 300,000 = 3 seconds."},
        {"text": "🔢 Antenna rotates 15° per second. Seconds to complete 360°?",
         "option_a": "20 s", "option_b": "24 s", "option_c": "30 s", "option_d": "36 s", "correct_option": "B",
         "explanation": "360 ÷ 15 = 24 seconds."},
        {"text": "📻 Signal frequency is 2.4 GHz. 1 GHz = 1,000 MHz. Value in MHz?",
         "option_a": "240 MHz", "option_b": "2,400 MHz", "option_c": "24,000 MHz", "option_d": "0.0024 MHz", "correct_option": "B",
         "explanation": "2.4 × 1,000 = 2,400 MHz."},
        {"text": "🌍 Earth's circumference ≈ 40,000 km. Signal travels 7.5 times around Earth. Distance?",
         "option_a": "200,000 km", "option_b": "250,000 km", "option_c": "300,000 km", "option_d": "350,000 km", "correct_option": "C",
         "explanation": "40,000 × 7.5 = 300,000 km."},
        {"text": "📊 Signal received 40% of the time. Out of 200 attempts, how many received?",
         "option_a": "60", "option_b": "70", "option_c": "80", "option_d": "90", "correct_option": "C",
         "explanation": "40% × 200 = 80 successful transmissions."},
        {"text": "⏱ Signal takes 22 minutes to reach Earth. Total round-trip time?",
         "option_a": "22 minutes", "option_b": "33 minutes", "option_c": "44 minutes", "option_d": "66 minutes", "correct_option": "C",
         "explanation": "22 there + 22 back = 44 minutes total."},
        {"text": "🔢 Data packet = 512 bytes. Ship sends 8 packets. Total data?",
         "option_a": "2,048 bytes", "option_b": "3,072 bytes", "option_c": "4,096 bytes", "option_d": "5,120 bytes", "correct_option": "C",
         "explanation": "512 × 8 = 4,096 bytes."},
        {"text": "📐 Signal dish is circular, radius = 5 m. Area? (π ≈ 3.14)",
         "option_a": "62.8 m²", "option_b": "75.6 m²", "option_c": "78.5 m²", "option_d": "80 m²", "correct_option": "C",
         "explanation": "Area = 3.14 × 5² = 3.14 × 25 = 78.5 m²."},
        {"text": "🧮 Signal strengths: 80, 65, 70, 55, 75. Average signal strength?",
         "option_a": "67", "option_b": "69", "option_c": "71", "option_d": "73", "correct_option": "B",
         "explanation": "(80+65+70+55+75) ÷ 5 = 345 ÷ 5 = 69."},
        {"text": "🔧 Antenna error = 12°. Each step reduces it by one-third. Error after 2 steps?",
         "option_a": "4°", "option_b": "4.33°", "option_c": "5°", "option_d": "5.33°", "correct_option": "D",
         "explanation": "Step 1: 12 × 2/3 = 8°. Step 2: 8 × 2/3 = 5.33°."},
    ],

    Subject.COMPUTER: [
        {"text": "📡 IP in 'IP address' stands for?",
         "option_a": "Internet Protocol", "option_b": "Internal Process", "option_c": "Input Program", "option_d": "Integrated Pathway", "correct_option": "A",
         "explanation": "IP = Internet Protocol — rules for addressing and routing data packets."},
        {"text": "🔢 Convert binary 1100 to decimal.",
         "option_a": "10", "option_b": "11", "option_c": "12", "option_d": "14", "correct_option": "C",
         "explanation": "1100 = 1×8 + 1×4 + 0×2 + 0×1 = 12."},
        {"text": "📂 Python code to check if 'Hello' has length 5?",
         "option_a": "length('Hello') == 5", "option_b": "size('Hello') == 5", "option_c": "len('Hello') == 5", "option_d": "count('Hello') == 5", "correct_option": "C",
         "explanation": "In Python, len() returns the length of a string. len('Hello') = 5."},
        {"text": "🔁 Sorting algorithm that repeatedly swaps adjacent out-of-order elements?",
         "option_a": "Binary Search", "option_b": "Merge Sort", "option_c": "Bubble Sort", "option_d": "Quick Sort", "correct_option": "C",
         "explanation": "Bubble Sort compares adjacent elements and swaps them if in the wrong order."},
        {"text": "🌐 HTTP stands for?",
         "option_a": "HyperText Transfer Protocol", "option_b": "High Tech Transmission Process", "option_c": "Hyper Terminal Transfer Protocol", "option_d": "HyperText Transport Process", "correct_option": "A",
         "explanation": "HTTP = HyperText Transfer Protocol — the foundation of web data communication."},
        {"text": "🔐 Encryption converts plain text into ___ text.",
         "option_a": "Binary", "option_b": "Cipher", "option_c": "Hex", "option_d": "Boolean", "correct_option": "B",
         "explanation": "Encryption converts readable plain text into unreadable cipher text."},
        {"text": "🧮 Function returns 'strong' if signal > 70, else 'weak'. Signal = 65. Output?",
         "option_a": "strong", "option_b": "weak", "option_c": "65", "option_d": "Error", "correct_option": "B",
         "explanation": "65 is not > 70, so the function returns 'weak'."},
        {"text": "🌐 Which OSI layer handles data ROUTING between networks?",
         "option_a": "Physical Layer", "option_b": "Data Link Layer", "option_c": "Network Layer", "option_d": "Transport Layer", "correct_option": "C",
         "explanation": "The Network Layer (Layer 3) handles logical addressing and routing."},
        {"text": "⚙ A function that calls ITSELF to solve a problem is called?",
         "option_a": "Iteration", "option_b": "Recursion", "option_c": "Compilation", "option_d": "Inheritance", "correct_option": "B",
         "explanation": "Recursion: a function calls itself to solve smaller versions of the same problem."},
        {"text": "📋 Array[1][2] means row ___, column ___.",
         "option_a": "Row 2, Column 3", "option_b": "Row 1, Column 2", "option_c": "Row 2, Column 1", "option_d": "Row 0, Column 2", "correct_option": "B",
         "explanation": "Array[row][column] — Array[1][2] = row index 1, column index 2."},
    ],

    Subject.PHYSICS: [
        {"text": "📻 Radio waves used for communication are a type of ___ radiation.",
         "option_a": "Sound", "option_b": "Nuclear", "option_c": "Electromagnetic", "option_d": "Thermal", "correct_option": "C",
         "explanation": "Radio waves are electromagnetic radiation — travel at speed of light, no medium needed."},
        {"text": "🌊 Speed is constant. Higher frequency means ___ wavelength.",
         "option_a": "Longer", "option_b": "Shorter", "option_c": "Equal", "option_d": "Unrelated", "correct_option": "B",
         "explanation": "speed = frequency × wavelength. Constant speed → higher frequency = shorter wavelength."},
        {"text": "🔊 Sound travels as a ___ wave.",
         "option_a": "Transverse", "option_b": "Electromagnetic", "option_c": "Longitudinal", "option_d": "Light", "correct_option": "C",
         "explanation": "Sound is a longitudinal wave — vibrations are parallel to the direction of travel."},
        {"text": "🌈 Light splits into colours through a prism. This is called ___.",
         "option_a": "Reflection", "option_b": "Refraction", "option_c": "Dispersion", "option_d": "Diffraction", "correct_option": "C",
         "explanation": "Dispersion splits white light into its spectrum of colours."},
        {"text": "⚡ Which has the HIGHEST frequency in the electromagnetic spectrum?",
         "option_a": "Radio waves", "option_b": "Microwaves", "option_c": "Visible light", "option_d": "Gamma rays", "correct_option": "D",
         "explanation": "Gamma rays have the highest frequency (and shortest wavelength)."},
        {"text": "📡 Wave frequency = 5 Hz, wavelength = 4 m. Wave speed?",
         "option_a": "5 m/s", "option_b": "9 m/s", "option_c": "20 m/s", "option_d": "25 m/s", "correct_option": "C",
         "explanation": "Wave speed = frequency × wavelength = 5 × 4 = 20 m/s."},
        {"text": "🔊 Echo received after 2 seconds. Sound speed = 340 m/s. Distance to object?",
         "option_a": "170 m", "option_b": "340 m", "option_c": "680 m", "option_d": "1,020 m", "correct_option": "B",
         "explanation": "Total = 340 × 2 = 680 m. Sound goes there AND back, so distance = 680 ÷ 2 = 340 m."},
        {"text": "🌡 Infrared waves have ___ frequency compared to visible light.",
         "option_a": "Same", "option_b": "Higher", "option_c": "Lower", "option_d": "Faster", "correct_option": "C",
         "explanation": "Infrared has lower frequency (and longer wavelength) than visible light."},
        {"text": "📻 The Doppler effect causes a change in ___ when the source moves.",
         "option_a": "Wave speed", "option_b": "Amplitude", "option_c": "Observed frequency", "option_d": "Wave type", "correct_option": "C",
         "explanation": "Doppler effect: moving source → change in observed frequency."},
        {"text": "🔵 Which type of wave CANNOT travel through a vacuum?",
         "option_a": "Light waves", "option_b": "Radio waves", "option_c": "Sound waves", "option_d": "X-rays", "correct_option": "C",
         "explanation": "Sound needs a medium (like air) to travel. It cannot travel through a vacuum."},
    ],

    Subject.CHEMISTRY: [
        {"text": "📡 Antenna coated with a polymer. Polymers are long chains of repeating units called?",
         "option_a": "Atoms", "option_b": "Monomers", "option_c": "Molecules", "option_d": "Electrons", "correct_option": "B",
         "explanation": "Polymers are long chains of monomers — small repeating molecules bonded together."},
        {"text": "🧪 Electrolytes conduct electricity when?",
         "option_a": "Solid", "option_b": "Heated", "option_c": "Dissolved in water or melted", "option_d": "Frozen", "correct_option": "C",
         "explanation": "Electrolytes conduct electricity only when dissolved or molten (ions move freely)."},
        {"text": "⚗ In which Period (row) of the periodic table is Carbon (C)?",
         "option_a": "Period 1", "option_b": "Period 2", "option_c": "Period 3", "option_d": "Period 4", "correct_option": "B",
         "explanation": "Carbon (atomic number 6) is in Period 2 of the periodic table."},
        {"text": "🔬 Fe₂O₃ — how many atoms are in ONE formula unit?",
         "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "6", "correct_option": "C",
         "explanation": "Fe₂O₃ = 2 iron + 3 oxygen = 5 atoms total."},
        {"text": "🌡 Which non-metal is a good conductor of electricity?",
         "option_a": "Sulphur", "option_b": "Phosphorus", "option_c": "Graphite (Carbon)", "option_d": "Iodine", "correct_option": "C",
         "explanation": "Graphite is a form of carbon and a non-metal that conducts electricity."},
        {"text": "⚗ Correctly balanced equation for burning hydrogen?",
         "option_a": "H₂ + O → H₂O", "option_b": "H₂ + O₂ → H₂O₂", "option_c": "2H₂ + O₂ → 2H₂O", "option_d": "H + O → HO", "correct_option": "C",
         "explanation": "2H₂ + O₂ → 2H₂O. Both sides: 4 hydrogen and 2 oxygen atoms — balanced."},
        {"text": "🧪 Indicator turns red in acid, blue in alkali. Water sample turns it RED. The water is?",
         "option_a": "Neutral", "option_b": "Alkaline", "option_c": "Acidic", "option_d": "Pure", "correct_option": "C",
         "explanation": "Red = acid (pH < 7). Blue/purple = alkali (pH > 7)."},
        {"text": "🔬 Na gives electron to Cl to form NaCl. This bond type is?",
         "option_a": "Covalent bond", "option_b": "Metallic bond", "option_c": "Ionic bond", "option_d": "Hydrogen bond", "correct_option": "C",
         "explanation": "Ionic bonds form between metals and non-metals through electron transfer."},
        {"text": "🌡 An exothermic reaction ___.",
         "option_a": "Absorbs heat from surroundings", "option_b": "Releases heat to surroundings", "option_c": "Requires electricity", "option_d": "Happens only in space", "correct_option": "B",
         "explanation": "Exothermic reactions release energy (as heat or light) to the surroundings."},
        {"text": "🧲 Elements in the same GROUP of the periodic table have similar ___.",
         "option_a": "Atomic masses", "option_b": "Numbers of neutrons", "option_c": "Chemical properties", "option_d": "Physical states", "correct_option": "C",
         "explanation": "Same group = same outer electrons = similar chemical properties."},
    ],

    Subject.GK: [
        {"text": "📡 Who invented the telephone?",
         "option_a": "Thomas Edison", "option_b": "Guglielmo Marconi", "option_c": "Alexander Graham Bell", "option_d": "Nikola Tesla", "correct_option": "C",
         "explanation": "Alexander Graham Bell invented the telephone in 1876."},
        {"text": "🌐 The World Wide Web was invented by?",
         "option_a": "Bill Gates", "option_b": "Tim Berners-Lee", "option_c": "Steve Jobs", "option_d": "Vint Cerf", "correct_option": "B",
         "explanation": "Tim Berners-Lee invented the World Wide Web in 1989 at CERN."},
        {"text": "📻 First to demonstrate wireless radio communication?",
         "option_a": "Alexander Bell", "option_b": "Michael Faraday", "option_c": "Guglielmo Marconi", "option_d": "James Maxwell", "correct_option": "C",
         "explanation": "Marconi demonstrated wireless telegraphy and sent the first transatlantic radio signal in 1901."},
        {"text": "🌍 The Sahara Desert — the world's largest hot desert — is on which continent?",
         "option_a": "Asia", "option_b": "South America", "option_c": "Australia", "option_d": "Africa", "correct_option": "D",
         "explanation": "The Sahara is in northern Africa, covering about 9.2 million km²."},
        {"text": "🔬 First to observe bacteria using a microscope?",
         "option_a": "Louis Pasteur", "option_b": "Robert Hooke", "option_c": "Antonie van Leeuwenhoek", "option_d": "Charles Darwin", "correct_option": "C",
         "explanation": "Antonie van Leeuwenhoek first observed bacteria in the 1670s."},
        {"text": "🌊 The Mariana Trench (deepest ocean point) is in which ocean?",
         "option_a": "Atlantic", "option_b": "Indian", "option_c": "Arctic", "option_d": "Pacific", "correct_option": "D",
         "explanation": "The Mariana Trench is in the western Pacific Ocean, reaching about 11 km depth."},
        {"text": "⚛ Who first proposed the modern atomic theory?",
         "option_a": "Isaac Newton", "option_b": "John Dalton", "option_c": "Marie Curie", "option_d": "Ernest Rutherford", "correct_option": "B",
         "explanation": "John Dalton proposed the modern atomic theory in the early 1800s."},
        {"text": "🌍 Capital city of Pakistan?",
         "option_a": "Karachi", "option_b": "Lahore", "option_c": "Islamabad", "option_d": "Peshawar", "correct_option": "C",
         "explanation": "Islamabad is the capital of Pakistan, built in the 1960s."},
        {"text": "🌿 Largest organ in the human body?",
         "option_a": "Liver", "option_b": "Brain", "option_c": "Lung", "option_d": "Skin", "correct_option": "D",
         "explanation": "The skin is the largest organ, covering the entire external surface."},
        {"text": "🏔 Tallest mountain on Earth?",
         "option_a": "K2", "option_b": "Kangchenjunga", "option_c": "Mount Everest", "option_d": "Makalu", "correct_option": "C",
         "explanation": "Mount Everest at 8,849 m is the tallest mountain on Earth."},
    ],
}


# ─── LEVEL 4 ── Life Support Critical Failure (MEDIUM) ───────────────────────

L4 = {

    Subject.MATH: [
        {"text": "💨 Oxygen drops from 21% to 15%. Drop in percentage points?",
         "option_a": "4", "option_b": "5", "option_c": "6", "option_d": "7", "correct_option": "C",
         "explanation": "21 − 15 = 6 percentage points."},
        {"text": "🌡 Safe cabin temperature: 18–24°C. Current temp = 11°C. How many degrees must it rise to reach minimum safe temp?",
         "option_a": "5°C", "option_b": "6°C", "option_c": "7°C", "option_d": "8°C", "correct_option": "C",
         "explanation": "18 − 11 = 7°C needed."},
        {"text": "💨 Air recycler: 150 litres/minute. Litres processed in 2.5 hours?",
         "option_a": "18,000 L", "option_b": "20,000 L", "option_c": "22,500 L", "option_d": "25,000 L", "correct_option": "C",
         "explanation": "2.5 hrs = 150 min. 150 × 150 = 22,500 L."},
        {"text": "🔢 Pressure dropped from 101 kPa to 87 kPa. Percentage decrease?",
         "option_a": "~12.5%", "option_b": "~13.9%", "option_c": "~15%", "option_d": "~16.5%", "correct_option": "B",
         "explanation": "Decrease = 14 kPa. % = 14/101 × 100 ≈ 13.9%."},
        {"text": "🧮 Life support systems: 400W + 350W + 250W. Ship provides only 900W. How much over the limit?",
         "option_a": "50 W", "option_b": "75 W", "option_c": "100 W", "option_d": "125 W", "correct_option": "C",
         "explanation": "400+350+250 = 1,000W. Over by 1,000 − 900 = 100 W."},
        {"text": "📊 Oxygen supply lasts 72 hours at normal usage. At 1.5× emergency usage, how long?",
         "option_a": "36 hours", "option_b": "42 hours", "option_c": "48 hours", "option_d": "54 hours", "correct_option": "C",
         "explanation": "72 ÷ 1.5 = 48 hours."},
        {"text": "🔧 Pressure valve allows 0.5 litres/second. Tank holds 900 litres. Time to empty?",
         "option_a": "25 minutes", "option_b": "30 minutes", "option_c": "35 minutes", "option_d": "40 minutes", "correct_option": "B",
         "explanation": "900 ÷ 0.5 = 1,800 seconds = 30 minutes."},
        {"text": "📐 Cylindrical oxygen tank: radius = 0.5 m, height = 2 m. Volume? (π ≈ 3.14)",
         "option_a": "1.57 m³", "option_b": "1.70 m³", "option_c": "2.00 m³", "option_d": "3.14 m³", "correct_option": "A",
         "explanation": "V = π × r² × h = 3.14 × 0.25 × 2 = 1.57 m³."},
        {"text": "🧮 Life support 4-digit error code uses ONLY odd digits (1,3,5,7,9). How many codes possible?",
         "option_a": "100", "option_b": "256", "option_c": "500", "option_d": "625", "correct_option": "D",
         "explanation": "5 choices × 5 × 5 × 5 = 625."},
        {"text": "🌡 Temperature rises from 20°C to 80°C. The increase is how many times the original value?",
         "option_a": "2×", "option_b": "3×", "option_c": "4×", "option_d": "5×", "correct_option": "B",
         "explanation": "Increase = 60°C. 60 ÷ 20 = 3× the original value."},
    ],

    Subject.COMPUTER: [
        {"text": "⚙ Data structure following First-In-First-Out (FIFO)?",
         "option_a": "Stack", "option_b": "Queue", "option_c": "Tree", "option_d": "Array", "correct_option": "B",
         "explanation": "A Queue follows FIFO — first item added is first to be removed."},
        {"text": "🔐 Emergency code needs uppercase AND digit. Which qualifies?",
         "option_a": "password", "option_b": "PASSWORD", "option_c": "Pass1234", "option_d": "12345678", "correct_option": "C",
         "explanation": "Pass1234 has uppercase (P) AND digits (1234)."},
        {"text": "🔁 Oxygen monitor checks every 5 seconds. How many checks in 2 minutes?",
         "option_a": "20", "option_b": "22", "option_c": "24", "option_d": "26", "correct_option": "C",
         "explanation": "2 min = 120 s. 120 ÷ 5 = 24 checks."},
        {"text": "📊 Correct Python dictionary syntax?",
         "option_a": "data = [oxygen: 21]", "option_b": "data = {oxygen: 21}", "option_c": "data = {'oxygen': 21}", "option_d": "data = (oxygen=21)", "correct_option": "C",
         "explanation": "Python dicts use curly braces with string keys in quotes: {'key': value}."},
        {"text": "🧮 Find the LARGEST in: [78, 92, 65, 88, 70].",
         "option_a": "88", "option_b": "90", "option_c": "92", "option_d": "78", "correct_option": "C",
         "explanation": "Scanning the list: largest is 92."},
        {"text": "⚙ A CLASS in Object-Oriented Programming is?",
         "option_a": "A running program", "option_b": "A blueprint/template for creating objects", "option_c": "A type of loop", "option_d": "A database table", "correct_option": "B",
         "explanation": "A class is a blueprint. Objects (instances) are created from the class."},
        {"text": "📋 Emergency log has 1,024 entries. How many bits needed to address all entries?",
         "option_a": "8 bits", "option_b": "9 bits", "option_c": "10 bits", "option_d": "12 bits", "correct_option": "C",
         "explanation": "2¹⁰ = 1,024. So 10-bit address references up to 1,024 entries."},
        {"text": "🔧 def oxygen(total, used): return (total-used)/total*100. total=100, used=21. Result?",
         "option_a": "21.0", "option_b": "79.0", "option_c": "0.79", "option_d": "Error", "correct_option": "B",
         "explanation": "(100−21)/100×100 = 79/100×100 = 79.0."},
        {"text": "🧮 In binary: 0101 + 0011 = ?",
         "option_a": "0111", "option_b": "1000", "option_c": "1001", "option_d": "0110", "correct_option": "B",
         "explanation": "5 + 3 = 8 = 1000 in binary."},
        {"text": "🌐 Which type of error occurs if data arrives OUT of order?",
         "option_a": "Syntax error", "option_b": "Runtime error", "option_c": "Logical error", "option_d": "Sequence/ordering error", "correct_option": "D",
         "explanation": "Data arriving out of order is a sequence/ordering error."},
    ],

    Subject.PHYSICS: [
        {"text": "💨 Pressure = Force per unit ___.",
         "option_a": "Volume", "option_b": "Mass", "option_c": "Area", "option_d": "Length", "correct_option": "C",
         "explanation": "Pressure = Force ÷ Area. SI unit is Pascal (Pa)."},
        {"text": "🌡 At constant temperature, P × V = constant. This is?",
         "option_a": "Charles' Law", "option_b": "Boyle's Law", "option_c": "Gay-Lussac's Law", "option_d": "Avogadro's Law", "correct_option": "B",
         "explanation": "Boyle's Law: P₁V₁ = P₂V₂ at constant temperature."},
        {"text": "🌡 Charles' Law: at constant pressure, gas volume is proportional to ___.",
         "option_a": "Mass", "option_b": "Absolute temperature (Kelvin)", "option_c": "Pressure", "option_d": "Number of molecules", "correct_option": "B",
         "explanation": "V/T = constant. Volume is proportional to absolute temperature in Kelvin."},
        {"text": "💨 Boyle's Law: P=101 kPa, V=50 m³. Volume halves. New pressure?",
         "option_a": "50.5 kPa", "option_b": "101 kPa", "option_c": "202 kPa", "option_d": "0 kPa", "correct_option": "C",
         "explanation": "P₁V₁=P₂V₂ → 101×50 = P₂×25 → P₂ = 202 kPa."},
        {"text": "🌡 At lower pressure (high altitude), water boils at ___ temperature.",
         "option_a": "Higher", "option_b": "Same", "option_c": "Lower", "option_d": "It cannot boil", "correct_option": "C",
         "explanation": "Lower pressure reduces the boiling point — water boils below 100°C at altitude."},
        {"text": "⚡ SI unit of heat energy?",
         "option_a": "Watt", "option_b": "Celsius", "option_c": "Joule", "option_d": "Kelvin", "correct_option": "C",
         "explanation": "Heat energy (like all energy) is measured in Joules (J)."},
        {"text": "💨 Oxygen molecules move faster when temperature increases. This motion energy is called?",
         "option_a": "Potential energy", "option_b": "Chemical energy", "option_c": "Nuclear energy", "option_d": "Kinetic energy", "correct_option": "D",
         "explanation": "Energy of moving molecules is kinetic energy."},
        {"text": "🌡 Absolute zero equals?",
         "option_a": "0°C", "option_b": "−100°C", "option_c": "−273°C (0 Kelvin)", "option_d": "−373°C", "correct_option": "C",
         "explanation": "Absolute zero = −273.15°C = 0 K. Particles have minimum possible energy."},
        {"text": "💨 A gas has ___ shape and ___ volume.",
         "option_a": "Fixed shape, fixed volume", "option_b": "No fixed shape, fixed volume", "option_c": "No fixed shape, no fixed volume", "option_d": "Fixed shape, no fixed volume", "correct_option": "C",
         "explanation": "Gases have no fixed shape and no fixed volume — expand to fill any container."},
        {"text": "🌡 Heat always flows from ___ to ___.",
         "option_a": "Cold → Hot", "option_b": "Hot → Cold", "option_c": "Heavy → Light", "option_d": "Large → Small", "correct_option": "B",
         "explanation": "Heat flows from hotter to cooler until thermal equilibrium."},
    ],

    Subject.CHEMISTRY: [
        {"text": "💨 Oxygen makes up approximately ___% of Earth's atmosphere.",
         "option_a": "10%", "option_b": "21%", "option_c": "50%", "option_d": "78%", "correct_option": "B",
         "explanation": "Oxygen ~21%, Nitrogen ~78% of Earth's atmosphere."},
        {"text": "🧪 CO₂ reacts with LiOH to remove it. This is an example of?",
         "option_a": "Combustion", "option_b": "Acid-base neutralisation", "option_c": "Decomposition", "option_d": "Precipitation", "correct_option": "B",
         "explanation": "CO₂ (acidic) + LiOH (base) = neutralisation reaction."},
        {"text": "🔬 Oxygen has 8 protons and is neutral. How many electrons?",
         "option_a": "6", "option_b": "7", "option_c": "8", "option_d": "10", "correct_option": "C",
         "explanation": "Neutral atom: protons = electrons. Oxygen has 8 protons = 8 electrons."},
        {"text": "🌡 Nitrogen's chemical symbol?",
         "option_a": "Ni", "option_b": "Ng", "option_c": "N", "option_d": "Ne", "correct_option": "C",
         "explanation": "Nitrogen's symbol is N. (Ni=Nickel, Ne=Neon.)"},
        {"text": "💨 Noble gases don't react because their outer electron shells are ___.",
         "option_a": "Empty", "option_b": "Full (stable)", "option_c": "Liquid at room temp", "option_d": "Conducting electricity", "correct_option": "B",
         "explanation": "Full outer electron shells make noble gases chemically stable and unreactive."},
        {"text": "🔬 Activated charcoal filters water by ___ impurities.",
         "option_a": "Reacting with and destroying", "option_b": "Adsorbing (trapping) on its surface", "option_c": "Boiling", "option_d": "Neutralising acids", "correct_option": "B",
         "explanation": "Activated charcoal adsorbs (traps) impurities on its large surface area."},
        {"text": "⚗ Elements in the same GROUP of the periodic table have similar chemical properties because they have the same ___.",
         "option_a": "Atomic masses", "option_b": "Number of neutrons", "option_c": "Number of outer electrons", "option_d": "Physical states", "correct_option": "C",
         "explanation": "Same group = same number of outer electrons = similar chemical properties."},
        {"text": "🌡 Which everyday reaction is exothermic?",
         "option_a": "Melting ice", "option_b": "Photosynthesis", "option_c": "Burning wood", "option_d": "Dissolving ammonium nitrate in water", "correct_option": "C",
         "explanation": "Burning wood (combustion) is exothermic — releases heat and light."},
        {"text": "🔬 Metals conduct heat because of?",
         "option_a": "High melting point", "option_b": "Free electrons that transfer energy", "option_c": "Heavy atomic mass", "option_d": "Shiny surface", "correct_option": "B",
         "explanation": "Metals have free (delocalised) electrons that transfer thermal energy quickly."},
        {"text": "🧪 Oxygen moves from lungs into blood (high to low concentration). This is called?",
         "option_a": "Osmosis", "option_b": "Diffusion", "option_c": "Filtration", "option_d": "Evaporation", "correct_option": "B",
         "explanation": "Diffusion: molecules move from high concentration to low concentration."},
    ],

    Subject.GK: [
        {"text": "💨 Approximate percentage of oxygen in air?",
         "option_a": "10%", "option_b": "21%", "option_c": "50%", "option_d": "78%", "correct_option": "B",
         "explanation": "About 21% of air is oxygen. About 78% is nitrogen."},
        {"text": "🌡 Normal human body temperature?",
         "option_a": "35.5°C", "option_b": "36°C", "option_c": "37°C", "option_d": "38°C", "correct_option": "C",
         "explanation": "Normal human body temperature ≈ 37°C (98.6°F)."},
        {"text": "🫀 Which organ controls breathing?",
         "option_a": "Heart", "option_b": "Lungs", "option_c": "Brain", "option_d": "Diaphragm", "correct_option": "C",
         "explanation": "The brainstem controls rate and depth of breathing automatically."},
        {"text": "🌍 Which is a RENEWABLE energy source?",
         "option_a": "Coal", "option_b": "Natural Gas", "option_c": "Solar Power", "option_d": "Nuclear Energy", "correct_option": "C",
         "explanation": "Solar power is renewable — the Sun provides an essentially unlimited energy supply."},
        {"text": "🌿 Which gas do plants take in during photosynthesis?",
         "option_a": "Oxygen (O₂)", "option_b": "Nitrogen (N₂)", "option_c": "Carbon dioxide (CO₂)", "option_d": "Hydrogen (H₂)", "correct_option": "C",
         "explanation": "Plants absorb CO₂ and release O₂ during photosynthesis."},
        {"text": "🏥 Study of the structure of the human body?",
         "option_a": "Biology", "option_b": "Anatomy", "option_c": "Physiology", "option_d": "Pathology", "correct_option": "B",
         "explanation": "Anatomy is the study of body structure. Physiology studies how it functions."},
        {"text": "🌊 Most abundant element in the human body by mass?",
         "option_a": "Carbon", "option_b": "Hydrogen", "option_c": "Nitrogen", "option_d": "Oxygen", "correct_option": "D",
         "explanation": "Oxygen makes up about 65% of the human body by mass (mainly in water)."},
        {"text": "❤ How many chambers does the human heart have?",
         "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "6", "correct_option": "C",
         "explanation": "The heart has 4 chambers: right atrium, right ventricle, left atrium, left ventricle."},
        {"text": "🌍 Who developed the theory of evolution by natural selection?",
         "option_a": "Gregor Mendel", "option_b": "Louis Pasteur", "option_c": "Charles Darwin", "option_d": "Carl Linnaeus", "correct_option": "C",
         "explanation": "Charles Darwin published evolution by natural selection in 'On the Origin of Species' (1859)."},
        {"text": "🔬 Which vitamin does the human body produce when exposed to sunlight?",
         "option_a": "Vitamin A", "option_b": "Vitamin B12", "option_c": "Vitamin C", "option_d": "Vitamin D", "correct_option": "D",
         "explanation": "Vitamin D is produced in the skin when exposed to UV light from the Sun."},
    ],
}


# ─── LEVEL 5 ── Engine Core & Landing System Failure (HARD) ──────────────────

L5 = {

    Subject.MATH: [
        {"text": "🚀 Decelerate from 7,800 m/s to 0 in 600 seconds. Deceleration (magnitude)?",
         "option_a": "11 m/s²", "option_b": "13 m/s²", "option_c": "15 m/s²", "option_d": "17 m/s²", "correct_option": "B",
         "explanation": "a = Δv ÷ t = 7,800 ÷ 600 = 13 m/s²."},
        {"text": "🔢 Solve: 3x² − 12 = 0. Values of x?",
         "option_a": "x = ±1", "option_b": "x = ±2", "option_c": "x = ±3", "option_d": "x = ±4", "correct_option": "B",
         "explanation": "3x² = 12 → x² = 4 → x = ±2."},
        {"text": "📐 Cone heat shield: radius=3 m, slant height=5 m. Curved surface area? (π≈3.14)",
         "option_a": "37.68 m²", "option_b": "47.10 m²", "option_c": "56.52 m²", "option_d": "62.80 m²", "correct_option": "B",
         "explanation": "Curved SA = π × r × l = 3.14 × 3 × 5 = 47.1 m²."},
        {"text": "📊 Descent angle ratio vertical:horizontal = 1:8. Vertical drop = 24 km. Horizontal distance?",
         "option_a": "144 km", "option_b": "168 km", "option_c": "192 km", "option_d": "216 km", "correct_option": "C",
         "explanation": "24 × 8 = 192 km."},
        {"text": "🧮 3 thruster bursts in ratio 2:3:5. Total fuel = 1,500 kg. Largest burst uses?",
         "option_a": "600 kg", "option_b": "700 kg", "option_c": "750 kg", "option_d": "800 kg", "correct_option": "C",
         "explanation": "5/10 × 1,500 = 750 kg."},
        {"text": "📉 Altitude starts at 100 km and halves every 5 minutes. Altitude after 20 minutes?",
         "option_a": "3.125 km", "option_b": "6.25 km", "option_c": "12.5 km", "option_d": "25 km", "correct_option": "B",
         "explanation": "5→50, 10→25, 15→12.5, 20→6.25 km."},
        {"text": "🔢 x + y = 20 AND x − y = 8. Find x.",
         "option_a": "12", "option_b": "13", "option_c": "14", "option_d": "16", "correct_option": "C",
         "explanation": "Add equations: 2x = 28 → x = 14."},
        {"text": "📐 Landing site at coordinates (3, 4) from origin. Straight-line distance from origin?",
         "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "7", "correct_option": "C",
         "explanation": "Distance = √(3²+4²) = √25 = 5. (3-4-5 right triangle.)"},
        {"text": "🚀 v = u + at. u=200 m/s, a=−15 m/s², t=10 s. Final speed v?",
         "option_a": "50 m/s", "option_b": "75 m/s", "option_c": "100 m/s", "option_d": "150 m/s", "correct_option": "A",
         "explanation": "v = 200 + (−15×10) = 200 − 150 = 50 m/s."},
        {"text": "💡 Landing probability increases 12% per repair. Starting 10%, probability after 5 repairs?",
         "option_a": "60%", "option_b": "68%", "option_c": "70%", "option_d": "72%", "correct_option": "C",
         "explanation": "10 + (5 × 12) = 70%."},
    ],

    Subject.COMPUTER: [
        {"text": "🧮 factorial(4) using recursion: factorial(n)=n×factorial(n−1), factorial(0)=1.",
         "option_a": "12", "option_b": "16", "option_c": "24", "option_d": "48", "correct_option": "C",
         "explanation": "4×3×2×1 = 24."},
        {"text": "🔢 Hexadecimal 1F in decimal?",
         "option_a": "15", "option_b": "25", "option_c": "31", "option_d": "35", "correct_option": "C",
         "explanation": "1F = 1×16 + 15 = 31."},
        {"text": "🔁 Maximum comparisons in binary search on a list of 16 items?",
         "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "8", "correct_option": "B",
         "explanation": "log₂(16) = 4."},
        {"text": "⚙ LandingSystem inherits from NavigationSystem. Which is TRUE?",
         "option_a": "LandingSystem cannot use NavigationSystem methods", "option_b": "LandingSystem inherits all NavigationSystem methods", "option_c": "NavigationSystem inherits from LandingSystem", "option_d": "They are unrelated", "correct_option": "B",
         "explanation": "Inheritance: child class inherits all parent class methods and attributes."},
        {"text": "📊 Ship transmits 1,024 bytes/second. Seconds to transmit 1 MB (1,048,576 bytes)?",
         "option_a": "512 s", "option_b": "1,024 s", "option_c": "1,048 s", "option_d": "2,048 s", "correct_option": "B",
         "explanation": "1,048,576 ÷ 1,024 = 1,024 seconds."},
        {"text": "🔐 XOR cipher: 1010 XOR 1100 = ?",
         "option_a": "0011", "option_b": "0101", "option_c": "0110", "option_d": "1000", "correct_option": "C",
         "explanation": "XOR: 1⊕1=0, 0⊕1=1, 1⊕0=1, 0⊕0=0 → 0110."},
        {"text": "🌐 Which OSI layer handles end-to-end error checking and reliable delivery?",
         "option_a": "Network (3)", "option_b": "Session (5)", "option_c": "Transport (4)", "option_d": "Physical (1)", "correct_option": "C",
         "explanation": "Transport Layer (4) handles end-to-end communication, error checking, and reliable delivery (TCP)."},
        {"text": "⚙ Time complexity of a basic linear search?",
         "option_a": "O(1)", "option_b": "O(log n)", "option_c": "O(n)", "option_d": "O(n²)", "correct_option": "C",
         "explanation": "Linear search checks each element one by one: O(n)."},
        {"text": "🔢 In 8-bit two's complement, binary representation of −1?",
         "option_a": "10000001", "option_b": "11111110", "option_c": "11111111", "option_d": "10000000", "correct_option": "C",
         "explanation": "Two's complement −1 = 11111111. Flip 00000001→11111110, add 1→11111111."},
        {"text": "🧮 A Directed Acyclic Graph (DAG) is defined as?",
         "option_a": "Has cycles connecting all nodes", "option_b": "Directed and has no cycles", "option_c": "Bidirectionally connected", "option_d": "Exactly one path between any two nodes", "correct_option": "B",
         "explanation": "A DAG has directed edges and no closed loops (acyclic)."},
    ],

    Subject.PHYSICS: [
        {"text": "🚀 KE = ½mv². Mass=2,000 kg, speed=100 m/s. Kinetic energy?",
         "option_a": "5,000,000 J", "option_b": "10,000,000 J", "option_c": "15,000,000 J", "option_d": "20,000,000 J", "correct_option": "B",
         "explanation": "KE = ½ × 2000 × 10,000 = 10,000,000 J (10 MJ)."},
        {"text": "🌡 Heat shield heats during re-entry by converting ___ energy to thermal energy.",
         "option_a": "Potential", "option_b": "Nuclear", "option_c": "Kinetic", "option_d": "Chemical", "correct_option": "C",
         "explanation": "As the ship decelerates, kinetic energy converts to heat due to air friction."},
        {"text": "⚡ Gravity assist uses ___ to speed up the ship.",
         "option_a": "Electromagnetic force", "option_b": "Gravitational potential energy", "option_c": "Nuclear energy", "option_d": "Chemical fuel only", "correct_option": "B",
         "explanation": "Gravity assist converts gravitational potential energy into kinetic energy."},
        {"text": "🌍 GPE = mgh. m=500 kg, g=10 m/s², h=200 m. Gravitational potential energy?",
         "option_a": "500,000 J", "option_b": "750,000 J", "option_c": "1,000,000 J", "option_d": "1,500,000 J", "correct_option": "C",
         "explanation": "GPE = 500 × 10 × 200 = 1,000,000 J (1 MJ)."},
        {"text": "🚀 Ship ejects gas at 3,000 m/s to move in the opposite direction. This is the principle of?",
         "option_a": "Momentum transfer", "option_b": "Gravity", "option_c": "Rocket propulsion", "option_d": "Centripetal force", "correct_option": "C",
         "explanation": "Rocket propulsion: Newton's Third Law — expelling mass backward propels rocket forward."},
        {"text": "💡 Momentum = mass × velocity. Mass=1,500 kg, velocity=200 m/s. Momentum?",
         "option_a": "150,000 kg·m/s", "option_b": "200,000 kg·m/s", "option_c": "250,000 kg·m/s", "option_d": "300,000 kg·m/s", "correct_option": "D",
         "explanation": "p = 1,500 × 200 = 300,000 kg·m/s."},
        {"text": "🌍 An orbiting ship is in a constant state of?",
         "option_a": "Zero gravity", "option_b": "Free fall while moving forward fast enough to curve around Earth", "option_c": "Escape from gravity", "option_d": "Uniform straight-line motion", "correct_option": "B",
         "explanation": "An orbit is continuous free fall — the ship falls toward Earth but its forward speed curves it around."},
        {"text": "⚡ Work = Force × Distance. Engine: 5,000 N over 300 m. Work done?",
         "option_a": "1,000,000 J", "option_b": "1,200,000 J", "option_c": "1,500,000 J", "option_d": "2,000,000 J", "correct_option": "C",
         "explanation": "W = 5,000 × 300 = 1,500,000 J (1.5 MJ)."},
        {"text": "🌙 Minimum speed to escape Earth's gravity is called?",
         "option_a": "Terminal velocity", "option_b": "Orbital velocity", "option_c": "Escape velocity", "option_d": "Critical velocity", "correct_option": "C",
         "explanation": "Escape velocity (~11.2 km/s) is the minimum speed to escape Earth's gravitational field."},
        {"text": "💡 Engine power = 500,000 W. Runs 60 seconds. Energy used?",
         "option_a": "500,000 J", "option_b": "15,000,000 J", "option_c": "30,000,000 J", "option_d": "60,000,000 J", "correct_option": "C",
         "explanation": "Energy = Power × Time = 500,000 × 60 = 30,000,000 J (30 MJ)."},
    ],

    Subject.CHEMISTRY: [
        {"text": "🔥 2H₂ + O₂ → ___. Combustion of hydrogen products?",
         "option_a": "H₂O₂", "option_b": "2H₂O", "option_c": "2HO", "option_d": "H₄O₂", "correct_option": "B",
         "explanation": "2H₂ + O₂ → 2H₂O (water). This releases enormous energy."},
        {"text": "🌡 Ceramics are good thermal insulators because?",
         "option_a": "They have free electrons", "option_b": "They are ionic/covalent with few free electrons to conduct heat", "option_c": "They are liquid at high temperatures", "option_d": "They react with oxygen", "correct_option": "B",
         "explanation": "No free electrons → slow heat conduction → good thermal insulator."},
        {"text": "⚗ Oxidation state of oxygen in water (H₂O)?",
         "option_a": "+1", "option_b": "+2", "option_c": "−2", "option_d": "0", "correct_option": "C",
         "explanation": "Oxygen almost always has oxidation state −2 in compounds."},
        {"text": "🔬 6.02 × 10²³ particles per mole is called Avogadro's number, named after?",
         "option_a": "Marie Curie", "option_b": "John Dalton", "option_c": "Amedeo Avogadro", "option_d": "Antoine Lavoisier", "correct_option": "C",
         "explanation": "Named after Amedeo Avogadro, the Italian scientist."},
        {"text": "🧪 Complete combustion of hydrocarbons produces?",
         "option_a": "Carbon monoxide and hydrogen", "option_b": "Carbon and water", "option_c": "Carbon dioxide and water", "option_d": "Carbon monoxide and water", "correct_option": "C",
         "explanation": "Complete combustion: Hydrocarbon + O₂ → CO₂ + H₂O."},
        {"text": "⚛ Nuclear power cell SPLITS atoms. This is called nuclear ___.",
         "option_a": "Fusion", "option_b": "Fission", "option_c": "Combustion", "option_d": "Ionisation", "correct_option": "B",
         "explanation": "Fission splits heavy atoms (like Uranium) releasing huge energy. Fusion joins atoms."},
        {"text": "🔬 Isotopes have the same number of ___ but different numbers of ___.",
         "option_a": "Neutrons; protons", "option_b": "Electrons; protons", "option_c": "Protons; neutrons", "option_d": "Protons; electrons", "correct_option": "C",
         "explanation": "Isotopes: same atomic number (protons), different mass numbers (different neutrons)."},
        {"text": "🌡 At 16,000°C (re-entry plasma), matter exists as?",
         "option_a": "Gas", "option_b": "Liquid", "option_c": "Solid", "option_d": "Plasma", "correct_option": "D",
         "explanation": "Plasma is the 4th state of matter — formed at extreme temperatures where atoms lose electrons."},
        {"text": "⚗ % by mass of Hydrogen in H₂O? (H=1, O=16)",
         "option_a": "~5.6%", "option_b": "~11.1%", "option_c": "~16.7%", "option_d": "~22.2%", "correct_option": "B",
         "explanation": "Mass of 2H=2. Molar mass=18. % = 2/18 × 100 = 11.1%."},
        {"text": "🔬 Silicon (atomic number 14): how many electrons in its outermost shell?",
         "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "6", "correct_option": "C",
         "explanation": "Si electron config: 2, 8, 4. Outermost shell has 4 electrons."},
    ],

    Subject.GK: [
        {"text": "🚀 First artificial satellite launched into space?",
         "option_a": "Explorer 1", "option_b": "Sputnik 1", "option_c": "Vostok 1", "option_d": "Apollo 1", "correct_option": "B",
         "explanation": "Sputnik 1, launched by the Soviet Union on October 4, 1957."},
        {"text": "👨‍🚀 First human to travel to space?",
         "option_a": "Neil Armstrong", "option_b": "Buzz Aldrin", "option_c": "Alan Shepard", "option_d": "Yuri Gagarin", "correct_option": "D",
         "explanation": "Yuri Gagarin orbited Earth once on April 12, 1961 (Vostok 1)."},
        {"text": "🌍 Force keeping planets in orbit around the Sun?",
         "option_a": "Electromagnetic force", "option_b": "Nuclear force", "option_c": "Gravity", "option_d": "Friction", "correct_option": "C",
         "explanation": "The Sun's massive gravitational pull curves planets' paths into orbits."},
        {"text": "⚛ Who developed the theory of general relativity?",
         "option_a": "Isaac Newton", "option_b": "Albert Einstein", "option_c": "Stephen Hawking", "option_d": "Niels Bohr", "correct_option": "B",
         "explanation": "Albert Einstein published the General Theory of Relativity in 1915."},
        {"text": "🌊 The Coriolis effect is caused by?",
         "option_a": "Earth's magnetic field", "option_b": "Earth's rotation", "option_c": "The Moon's gravity", "option_d": "Temperature differences", "correct_option": "B",
         "explanation": "Earth's rotation deflects moving air and water — the Coriolis effect."},
        {"text": "🔭 The Hubble Space Telescope is operated by?",
         "option_a": "ESA only", "option_b": "ISRO", "option_c": "NASA and ESA jointly", "option_d": "NASA alone", "correct_option": "C",
         "explanation": "Hubble is a joint NASA and ESA project."},
        {"text": "💻 Father of computer science and artificial intelligence?",
         "option_a": "Charles Babbage", "option_b": "Ada Lovelace", "option_c": "Alan Turing", "option_d": "John von Neumann", "correct_option": "C",
         "explanation": "Alan Turing — famous for the Turing Machine and Turing Test."},
        {"text": "🌍 Climate change is largely caused by increasing levels of?",
         "option_a": "Oxygen", "option_b": "Nitrogen", "option_c": "Carbon dioxide (CO₂)", "option_d": "Argon", "correct_option": "C",
         "explanation": "Rising CO₂ from fossil fuels enhances the greenhouse effect, causing global warming."},
        {"text": "🔬 CRISPR technology is used to?",
         "option_a": "Build faster computers", "option_b": "Edit genes in DNA", "option_c": "Explore deep oceans", "option_d": "Manufacture medicines chemically", "correct_option": "B",
         "explanation": "CRISPR-Cas9 is a gene-editing tool that modifies DNA sequences precisely."},
        {"text": "🚀 SpaceX's reusable rocket is called?",
         "option_a": "Ariane 5", "option_b": "Saturn V", "option_c": "Falcon 9", "option_d": "Atlas V", "correct_option": "C",
         "explanation": "Falcon 9 is SpaceX's reusable rocket whose first stage lands back after launch."},
    ],
}


# ─── Master map ───────────────────────────────────────────────────────────────

ALL_QUESTIONS = {1: L1, 2: L2, 3: L3, 4: L4, 5: L5}


class Command(BaseCommand):
    help = (
        "Seeds the full story-driven question bank: "
        "'Mars Return Mission – Space Station Emergency'. "
        "10 questions × 5 subjects × 5 levels = 250 questions. Safe to re-run."
    )

    def handle(self, *args, **options):
        created_total = 0
        skipped_total = 0

        for level, subjects in ALL_QUESTIONS.items():
            difficulty = LEVEL_DIFFICULTY[level]
            for subject, questions in subjects.items():
                for q in questions:
                    _, created = Question.objects.get_or_create(
                        level=level,
                        subject=subject,
                        difficulty=difficulty,
                        text=q["text"],
                        defaults={
                            "option_a": q["option_a"],
                            "option_b": q["option_b"],
                            "option_c": q["option_c"],
                            "option_d": q["option_d"],
                            "correct_option": q["correct_option"],
                            "explanation": q["explanation"],
                        },
                    )
                    if created:
                        created_total += 1
                    else:
                        skipped_total += 1

        self.stdout.write(self.style.SUCCESS(
            f"\n✅ Seeding complete!\n"
            f"   Created : {created_total} questions\n"
            f"   Skipped : {skipped_total} already existed\n"
            f"   Total   : {created_total + skipped_total}\n"
        ))
