# Generated by Django 6.0.5 on 2026-05-24 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.PositiveSmallIntegerField(help_text='Which question (1–15) triggered this interaction.')),
                ('subject', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('computer', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('gk', 'General Knowledge')], max_length=20)),
                ('request_type', models.CharField(choices=[('hint', 'Hint'), ('explanation', 'Explanation'), ('wrong_answer', 'Wrong Answer Analysis')], max_length=20)),
                ('user_message', models.TextField(blank=True)),
                ('hint_text', models.TextField(blank=True)),
                ('explanation_text', models.TextField(blank=True)),
                ('youtube_title', models.CharField(blank=True, max_length=512)),
                ('youtube_url', models.URLField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='game.gamesession')),
            ],
            options={
                'db_table': 'ai_interactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strongest_subject', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('computer', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('gk', 'General Knowledge')], max_length=20)),
                ('weakest_subject', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('computer', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('gk', 'General Knowledge')], max_length=20)),
                ('summary', models.TextField()),
                ('improvement_suggestions', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='game.gamesession')),
            ],
            options={
                'db_table': 'ai_reports',
            },
        ),
    ]
